site_name: CC Workshops for AWS
theme:
  name: material
#  name: readthedocs
#  custom_dir: mkdocs-material/material
#  static_templates:
#    - 404.html
  include_search_page: true
  search_index_only: false
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Ubuntu
    code: Ubuntu Mono
dev_addr: '0.0.0.0:8001'

repo_url: http://github.com/ccortezb/awsworkshops
site_url: https://ccortezb.github.io/awsworkshops
site_description: 'Laboratorios Guiados de AWS por Carlos Cortez'

nav:
- Home: index.md
- About: about.md
- AWS EKS desde Cero:
  - Bienvenido: eksdesdecero/ekswelcome.md
  - Lab 1 EKS: eksdesdecero/ekslab1.md


plugins:
  - search
